const STORAGE_KEY='orderdesk_orders_v1';
const REMEMBER_KEY='orderdesk_remembered_login';
const REMEMBER_UNTIL_KEY='orderdesk_remember_until';
const rememberedUntil=()=>Number(localStorage.getItem(REMEMBER_UNTIL_KEY)||0);
const rememberActive=()=>rememberedUntil()>Date.now();
const authStorage={getItem(key){if(rememberActive())return localStorage.getItem(key)||sessionStorage.getItem(key);const session=sessionStorage.getItem(key);localStorage.removeItem(key);return session},setItem(key,value){if(rememberActive()){localStorage.setItem(key,value);sessionStorage.removeItem(key)}else{sessionStorage.setItem(key,value);localStorage.removeItem(key)}},removeItem(key){localStorage.removeItem(key);sessionStorage.removeItem(key)}};
const cfg=window.APP_CONFIG||{};
const client=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{storage:authStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const today=new Date();
const iso=(d)=>d.toISOString().slice(0,10);
const addDays=(n)=>{const d=new Date();d.setDate(d.getDate()+n);return iso(d)};
const seedOrders=[
  {id:'OD20260908001',customer:'杭州新锐生物科技',contact:'张经理 138****6688',requirement:'重组蛋白试剂盒 A 型，10 套；随货提供质检报告',amount:28600,paid:0,owner:'林岚',dueDate:addDays(2),priority:'紧急',status:'待发货',contract:'已签订',invoice:'已开票',shipping:'备货中',payment:'待付款',carrier:'',tracking:'',feedback:'',notes:'客户要求周五前到货',updated:Date.now()-120000},
  {id:'OD20260906002',customer:'苏州澄明医疗器械',contact:'王工 139****2810',requirement:'定制耗材 500 件，型号 CM-02',amount:48500,paid:20000,owner:'周越',dueDate:addDays(-1),priority:'普通',status:'待回款',contract:'已签订',invoice:'已寄出',shipping:'已签收',payment:'部分付款',carrier:'顺丰',tracking:'SF1483027365210',feedback:'产品已验收，等待财务尾款审批',notes:'尾款 28500 元',updated:Date.now()-3600000},
  {id:'OD20260903003',customer:'上海柏研实验室',contact:'陈老师 136****9921',requirement:'检测服务 24 个样本，出具中英文报告',amount:12000,paid:12000,owner:'林岚',dueDate:addDays(-3),priority:'普通',status:'已完成',contract:'无需合同',invoice:'已开票',shipping:'无需发货',payment:'已付清',carrier:'',tracking:'',feedback:'结果清晰，交付及时，满意',notes:'',updated:Date.now()-86400000},
  {id:'OD20260901004',customer:'南京禾创生物',contact:'赵主管 137****5156',requirement:'实验耗材年度框架采购，首批 80 箱',amount:76000,paid:0,owner:'周越',dueDate:addDays(8),priority:'普通',status:'合同处理中',contract:'待客户确认',invoice:'未申请',shipping:'未备货',payment:'未付款',carrier:'',tracking:'',feedback:'',notes:'合同法务条款待确认',updated:Date.now()-172800000}
];
const legacyOrders=loadLegacyOrders();
let orders=[];
const selectedOrderIds=new Set();
let pendingImport=null;
const pendingDocumentFiles={contract:[],invoice:[]};
let modalDocuments={contract:[],invoice:[]};
let currentView='dashboard';
const $=(id)=>document.getElementById(id);
function loadLegacyOrders(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):[]}catch{return[]}}
async function loadSharedOrders(){const {data,error}=await client.from('order_records').select('id,data,updated_at').order('updated_at',{ascending:false});if(error)throw error;orders=(data||[]).map(row=>({...row.data,id:row.id,updated:Number(row.updated_at)}));if(!orders.length&&legacyOrders.length){const rows=legacyOrders.map(o=>({id:o.id,data:o,updated_at:Number(o.updated||Date.now())}));const imported=await client.from('order_records').upsert(rows,{onConflict:'id'});if(imported.error)throw imported.error;orders=[...legacyOrders]}renderAll()}
async function persistOrder(order){const {error}=await client.from('order_records').upsert({id:order.id,data:order,updated_at:Number(order.updated)},{onConflict:'id'});if(error)throw error;const i=orders.findIndex(x=>x.id===order.id);if(i>=0)orders[i]=order;else orders.unshift(order);renderAll()}
async function persistOrdersBatch(importedOrders){if(!importedOrders.length)return;const existingById=new Map(orders.map(order=>[order.id,order]));const safeOrders=importedOrders.map(order=>({...order,documents:order.documents||existingById.get(order.id)?.documents||{contract:[],invoice:[]}}));const rows=safeOrders.map(order=>({id:order.id,data:order,updated_at:Number(order.updated)}));const {error}=await client.from('order_records').upsert(rows,{onConflict:'id'});if(error)throw error;const merged=new Map(orders.map(order=>[order.id,order]));safeOrders.forEach(order=>merged.set(order.id,order));orders=[...merged.values()].sort((a,b)=>Number(b.updated)-Number(a.updated));renderAll()}
async function removeSharedOrders(ids){const unique=[...new Set(ids)].filter(Boolean);if(!unique.length)return;const removed=new Set(unique);const documentPaths=orders.filter(order=>removed.has(order.id)).flatMap(order=>{const documents=OrderDocumentUtils.normalizeDocuments(order);return[...documents.contract,...documents.invoice].map(file=>file.path)});const {error}=await client.from('order_records').delete().in('id',unique);if(error)throw error;if(documentPaths.length){const result=await client.storage.from('order-documents').remove(documentPaths);if(result.error)console.warn('Order documents could not be removed',result.error)}orders=orders.filter(o=>!removed.has(o.id));unique.forEach(id=>selectedOrderIds.delete(id));renderAll()}
async function removeSharedOrder(id){await removeSharedOrders([id])}
function money(n){return '¥'+Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2})}
function shortDate(s){if(!s)return '—';const d=new Date(s+'T00:00:00');return `${d.getMonth()+1}月${d.getDate()}日`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusClass(s){if(['已完成','已签订','已开票','已签收','已付清'].includes(s))return 'green';if(['待回款','待发货','合同处理中','部分付款','备货中'].includes(s))return 'amber';if(['售后处理中','已取消','逾期'].includes(s))return 'red';return 'blue'}
function pill(s){return `<span class="status-pill ${statusClass(s)}">${esc(s)}</span>`}
function isOverdue(o){return o.status!=='已完成'&&o.status!=='已取消'&&o.dueDate&&o.dueDate<iso(today)}
function reminders(){const rows=[];orders.forEach(o=>{if(isOverdue(o))rows.push({level:'red',type:'交付逾期',title:`${o.customer} · ${o.id}`,detail:`原计划 ${shortDate(o.dueDate)} 交付，目前状态：${o.status}`,id:o.id});if(o.payment!=='已付清'&&o.status!=='已取消'&&Number(o.amount)>Number(o.paid))rows.push({level:o.dueDate<iso(today)?'red':'amber',type:'待回款',title:`${o.customer} · 待收 ${money(o.amount-o.paid)}`,detail:`订单 ${o.id}，当前：${o.payment}`,id:o.id});if(o.status==='售后处理中')rows.push({level:'red',type:'客户反馈',title:o.customer,detail:o.feedback||'存在待处理的客户反馈',id:o.id});});return rows}
function orderTable(list,limit,selectable=false){const data=limit?list.slice(0,limit):list;if(!data.length)return `<div class="empty-state"><b>暂时没有符合条件的订单</b>调整筛选条件，或新建一笔订单。</div>`;const selectHead=selectable?'<th class="select-cell"><label class="select-all-label"><input id="selectAllOrders" type="checkbox" aria-label="全选当前订单列表"><span>全选</span></label></th>':'';return `<table class="data-table"><thead><tr>${selectHead}<th>订单 / 客户</th><th>金额</th><th>合同</th><th>发票</th><th>发货</th><th>回款</th><th>交付日期</th></tr></thead><tbody>${data.map(o=>`<tr data-order-id="${esc(o.id)}">${selectable?`<td class="select-cell"><input class="order-select" type="checkbox" data-select-order-id="${esc(o.id)}" aria-label="选择订单 ${esc(o.id)}" ${selectedOrderIds.has(o.id)?'checked':''}></td>`:''}<td class="order-name"><strong>${esc(o.customer)}${o.priority==='紧急'?'<span class="priority">紧急</span>':''}</strong><span>${esc(o.id)} · ${esc(o.requirement)}</span></td><td class="amount">${money(o.amount)}</td><td>${pill(o.contract)}</td><td>${pill(o.invoice)}</td><td>${pill(o.shipping)}</td><td>${pill(o.payment)}</td><td class="${isOverdue(o)?'overdue':''}">${shortDate(o.dueDate)}</td></tr>`).join('')}</tbody></table>`}
function renderDashboard(){const open=orders.filter(o=>!['已完成','已取消'].includes(o.status));const unpaid=orders.reduce((s,o)=>s+Math.max(0,Number(o.amount)-Number(o.paid)),0);const rs=reminders();const metrics=[['全部订单',orders.length,'本月累计','▤','#3066e8','#eef4ff','all'],['进行中',open.length,'需要持续跟进','↻','#9a681c','#fff5df','__active'],['待发货',orders.filter(o=>['待发货','备货中','部分发货'].includes(o.shipping)).length,'检查交付计划','⇢','#7657d6','#f1edff','__shipping'],['待回款',money(unpaid),'未收金额','¥','#16866b','#e8f7f2','__payment']];$('metricGrid').innerHTML=metrics.map(m=>`<button type="button" class="metric-card" data-metric-filter="${m[6]}" aria-label="查看${m[0]}列表" style="--accent:${m[4]};--accent-soft:${m[5]}"><div class="metric-top"><span class="metric-label">${m[0]}</span><span class="metric-icon">${m[3]}</span></div><div class="metric-value">${m[1]}</div><div class="metric-note">${m[2]}</div></button>`).join('');document.querySelectorAll('[data-metric-filter]').forEach(card=>card.onclick=()=>{switchView('orders');$('statusFilter').value=card.dataset.metricFilter;$('orderSearch').value='';$('ownerFilter').value='all';renderOrders()});$('recentOrders').innerHTML=orderTable([...orders].sort((a,b)=>b.updated-a.updated),4);$('todoBadge').textContent=rs.length;$('navReminderCount').textContent=rs.length;$('todoList').classList.toggle('scrollable',rs.length>6);$('todoList').innerHTML=rs.map(r=>`<button type="button" class="todo-item ${r.level}" data-todo-order-id="${esc(r.id)}" aria-label="查看订单 ${esc(r.id)}：${esc(r.type)}"><span class="todo-dot"></span><span class="todo-content"><strong>${esc(r.type)} · ${esc(r.title)}</strong><span>${esc(r.detail)}</span></span></button>`).join('')||'<div class="empty-state"><b>没有待处理事项</b>当前订单进展顺利。</div>';document.querySelectorAll('[data-todo-order-id]').forEach(item=>item.onclick=()=>openModal(item.dataset.todoOrderId))}
function normalizeLogistics(o){if(Array.isArray(o.logistics))return o.logistics.filter(x=>x&&(x.carrier||x.tracking));return o.carrier||o.tracking?[{carrier:o.carrier||'',tracking:o.tracking||''}]:[]}
function addLogisticsRow(item={}){const row=document.createElement('div');row.className='logistics-row';row.innerHTML=`<input class="logistics-carrier" aria-label="快递公司" placeholder="快递公司，如顺丰" value="${esc(item.carrier||'')}"><input class="logistics-tracking" aria-label="快递单号" placeholder="对应的快递单号" value="${esc(item.tracking||'')}"><button type="button" class="remove-logistics" aria-label="删除这条物流信息">×</button>`;row.querySelector('.remove-logistics').onclick=()=>{if($('logisticsRows').children.length===1){row.querySelectorAll('input').forEach(input=>input.value='')}else row.remove()};$('logisticsRows').appendChild(row)}
function renderLogisticsRows(items=[]){$('logisticsRows').innerHTML='';(items.length?items:[{}]).forEach(addLogisticsRow)}
function getLogistics(){return [...document.querySelectorAll('.logistics-row')].map(row=>({carrier:row.querySelector('.logistics-carrier').value.trim(),tracking:row.querySelector('.logistics-tracking').value.trim()})).filter(x=>x.carrier||x.tracking)}
function resetDocumentState(order=null){modalDocuments=OrderDocumentUtils.normalizeDocuments(order);pendingDocumentFiles.contract=[];pendingDocumentFiles.invoice=[];$('contractFileInput').value='';$('invoiceFileInput').value=''}
function renderDocumentList(kind){const container=$(kind==='contract'?'contractDocumentList':'invoiceDocumentList');const saved=modalDocuments[kind]||[];const pending=pendingDocumentFiles[kind]||[];if(!saved.length&&!pending.length){container.innerHTML='<div class="document-empty">暂未上传附件</div>';return}container.innerHTML=saved.map((doc,index)=>`<div class="document-item"><div class="document-item-name"><strong>${esc(doc.name)}</strong><span>${OrderDocumentUtils.formatSize(doc.size)} · 已保存</span></div><button type="button" data-download-document="${kind}-${index}">下载</button></div>`).join('')+pending.map((file,index)=>`<div class="document-item"><div class="document-item-name"><strong>${esc(file.name)}</strong><span>${OrderDocumentUtils.formatSize(file.size)}</span></div><span class="pending-file-badge">保存订单后上传</span><button type="button" class="remove-pending-file" data-remove-pending="${kind}-${index}">移除</button></div>`).join('');container.querySelectorAll('[data-download-document]').forEach(button=>button.onclick=()=>{const [fileKind,index]=button.dataset.downloadDocument.split('-');downloadOrderDocument(modalDocuments[fileKind][Number(index)])});container.querySelectorAll('[data-remove-pending]').forEach(button=>button.onclick=()=>{const [fileKind,index]=button.dataset.removePending.split('-');pendingDocumentFiles[fileKind].splice(Number(index),1);renderDocumentList(fileKind)})}
function renderDocumentLists(){renderDocumentList('contract');renderDocumentList('invoice')}
function queueDocumentFiles(kind,fileList){const {valid,errors}=OrderDocumentUtils.validateFiles(fileList);pendingDocumentFiles[kind].push(...valid);renderDocumentList(kind);if(errors.length)toast(errors[0]+(errors.length>1?`，另有 ${errors.length-1} 个文件未添加`:''))}
function fileContentType(file){if(file.type)return file.type;const extension=file.name.split('.').pop().toLowerCase();return{pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}[extension]||'application/octet-stream'}
async function downloadOrderDocument(fileRecord){if(!fileRecord?.path)return;try{const {data,error}=await client.storage.from('order-documents').createSignedUrl(fileRecord.path,120);if(error)throw error;const link=document.createElement('a');link.href=data.signedUrl;link.download=fileRecord.name;link.target='_blank';link.rel='noopener';link.click()}catch(error){console.error(error);toast('附件下载失败，请稍后重试')}}
async function uploadPendingDocuments(order){const count=pendingDocumentFiles.contract.length+pendingDocumentFiles.invoice.length;if(!count)return{order:{...order,documents:modalDocuments},uploadedPaths:[]};const {data,error:userError}=await client.auth.getUser();if(userError||!data.user)throw userError||new Error('登录状态已失效');const documents={contract:[...modalDocuments.contract],invoice:[...modalDocuments.invoice]};const uploadedPaths=[];try{for(const kind of ['contract','invoice']){for(const [index,file] of pendingDocumentFiles[kind].entries()){const path=OrderDocumentUtils.buildPath(data.user.id,order.id,kind,file,index);const {error}=await client.storage.from('order-documents').upload(path,file,{cacheControl:'3600',upsert:false,contentType:fileContentType(file)});if(error)throw error;uploadedPaths.push(path);documents[kind].push({name:file.name,path,size:file.size,type:fileContentType(file),uploadedAt:new Date().toISOString()})}}return{order:{...order,documents},uploadedPaths}}catch(error){if(uploadedPaths.length)await client.storage.from('order-documents').remove(uploadedPaths);throw error}}
function updateBatchActions(filtered=[]){const validIds=new Set(orders.map(o=>o.id));[...selectedOrderIds].forEach(id=>{if(!validIds.has(id))selectedOrderIds.delete(id)});$('selectedOrderCount').textContent=selectedOrderIds.size;$('exportSelectedBtn').disabled=selectedOrderIds.size===0;$('batchDeleteBtn').disabled=selectedOrderIds.size===0;$('batchActions').classList.toggle('active',selectedOrderIds.size>0);const selectAll=$('selectAllOrders');if(selectAll){const visibleIds=filtered.map(o=>o.id);const selectedVisible=visibleIds.filter(id=>selectedOrderIds.has(id)).length;selectAll.checked=visibleIds.length>0&&selectedVisible===visibleIds.length;selectAll.indeterminate=selectedVisible>0&&selectedVisible<visibleIds.length}}
function renderOrders(){const q=$('orderSearch').value.trim().toLowerCase();const st=$('statusFilter').value;const ow=$('ownerFilter').value;const matchesStatus=o=>st==='all'||(st==='__active'&&!['已完成','已取消'].includes(o.status))||(st==='__shipping'&&['待发货','备货中','部分发货'].includes(o.shipping))||(st==='__payment'&&o.status!=='已取消'&&Number(o.amount)>Number(o.paid))||o.status===st;const filtered=orders.filter(o=>matchesStatus(o)&&(ow==='all'||o.owner===ow)&&(!q||[o.id,o.customer,o.requirement,...normalizeLogistics(o).flatMap(x=>[x.carrier,x.tracking])].join(' ').toLowerCase().includes(q)));$('ordersTable').innerHTML=orderTable(filtered,null,true);document.querySelectorAll('#ordersTable [data-order-id]').forEach(row=>row.onclick=e=>{if(!e.target.closest('input,button,a,label'))openModal(row.dataset.orderId)});document.querySelectorAll('.order-select').forEach(box=>box.onchange=()=>{box.checked?selectedOrderIds.add(box.dataset.selectOrderId):selectedOrderIds.delete(box.dataset.selectOrderId);updateBatchActions(filtered)});const selectAll=$('selectAllOrders');if(selectAll)selectAll.onchange=()=>{filtered.forEach(o=>selectAll.checked?selectedOrderIds.add(o.id):selectedOrderIds.delete(o.id));renderOrders()};updateBatchActions(filtered)}
function renderCustomers(){const map={};orders.forEach(o=>{map[o.customer]??={name:o.customer,contact:o.contact,count:0,total:0,unpaid:0};map[o.customer].count++;map[o.customer].total+=Number(o.amount);map[o.customer].unpaid+=Math.max(0,Number(o.amount)-Number(o.paid))});$('customerGrid').innerHTML=Object.values(map).map(c=>`<article class="customer-card"><div class="customer-card-head"><div class="customer-logo">${esc(c.name[0])}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.contact||'暂无联系人')}</p></div></div><div class="customer-stats"><div><span>订单 / 累计</span><strong>${c.count} 笔 · ${money(c.total)}</strong></div><div><span>未回款</span><strong class="${c.unpaid?'money-red':''}">${money(c.unpaid)}</strong></div></div></article>`).join('')||'<div class="empty-state"><b>暂无客户</b>客户会随订单自动汇总。</div>'}
function renderReminders(){const rs=reminders();$('allReminders').innerHTML=rs.map(r=>`<div class="reminder-row"><span>${pill(r.type)}</span><div><strong>${esc(r.title)}</strong><p>${esc(r.detail)}</p></div><button class="secondary" data-edit-reminder="${r.id}">查看订单</button></div>`).join('')||'<div class="empty-state"><b>没有待办提醒</b>所有订单均在计划内。</div>';document.querySelectorAll('[data-edit-reminder]').forEach(b=>b.onclick=()=>openModal(b.dataset.editReminder))}
function renderOwners(){const current=$('ownerFilter').value;const owners=[...new Set(orders.map(o=>o.owner).filter(Boolean))];$('ownerFilter').innerHTML='<option value="all">全部负责人</option>'+owners.map(x=>`<option>${esc(x)}</option>`).join('');if(owners.includes(current))$('ownerFilter').value=current}
function renderAll(){renderOwners();renderDashboard();renderOrders();renderCustomers();renderReminders()}
function switchView(name){currentView=name;document.querySelectorAll('.view-section').forEach(v=>v.classList.add('hidden'));$(`${name}View`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('pageTitle').textContent={dashboard:'工作台',orders:'订单管理',customers:'客户管理',reminders:'待办提醒'}[name];document.querySelector('.sidebar').classList.remove('open')}
function openModal(id){$('orderForm').reset();$('editingId').value='';$('owner').value='管理员';$('modalTitle').textContent='新建订单';$('deleteOrder').classList.add('hidden');renderLogisticsRows();let order=null;if(id){order=orders.find(x=>x.id===id);if(!order)return;$('editingId').value=order.id;$('modalTitle').textContent=`编辑订单 ${order.id}`;$('deleteOrder').classList.remove('hidden');const values={customerName:order.customer,contact:order.contact,requirement:order.requirement,amount:order.amount,owner:order.owner,dueDate:order.dueDate,priority:order.priority,status:order.status,contract:order.contract,invoice:order.invoice,shipping:order.shipping,payment:order.payment,paidAmount:order.paid,feedback:order.feedback,notes:order.notes};Object.entries(values).forEach(([k,v])=>$(k).value=v??'');renderLogisticsRows(normalizeLogistics(order))}resetDocumentState(order);renderDocumentLists();$('orderModal').classList.remove('hidden');setTimeout(()=>$('customerName').focus(),50)}
function closeModal(){$('orderModal').classList.add('hidden');resetDocumentState()}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function formOrder(){const oldId=$('editingId').value;const logistics=getLogistics();return{id:oldId||`OD${iso(today).replaceAll('-','')}${String(Date.now()).slice(-3)}`,customer:$('customerName').value.trim(),contact:$('contact').value.trim(),requirement:$('requirement').value.trim(),amount:Number($('amount').value||0),paid:Number($('paidAmount').value||0),owner:$('owner').value.trim()||'管理员',dueDate:$('dueDate').value,priority:$('priority').value,status:$('status').value,contract:$('contract').value,invoice:$('invoice').value,shipping:$('shipping').value,payment:$('payment').value,logistics,carrier:logistics[0]?.carrier||'',tracking:logistics[0]?.tracking||'',feedback:$('feedback').value.trim(),notes:$('notes').value.trim(),documents:{contract:[...modalDocuments.contract],invoice:[...modalDocuments.invoice]},updated:Date.now()}}
function exportCsv(list){if(!list.length)return;const head=['订单编号','客户名称','联系人','客户需求','订单金额','已收金额','负责人','预计交付','总体状态','合同','发票','发货','回款','物流信息','客户反馈','备注'];const rows=list.map(o=>[o.id,o.customer,o.contact,o.requirement,o.amount,o.paid,o.owner,o.dueDate,o.status,o.contract,o.invoice,o.shipping,o.payment,normalizeLogistics(o).map(x=>`${x.carrier}：${x.tracking}`).join('；'),o.feedback,o.notes]);const csv='\ufeff'+[head,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`订单数据_${iso(today)}_${list.length}条.csv`;a.click();URL.revokeObjectURL(a.href);toast(`已导出 ${list.length} 条订单`)}
function closeImportModal(){$('importModal').classList.add('hidden');pendingImport=null;$('orderFileInput').value=''}
function importExample(item){const order=item.order;return `第 ${item.rowNumber} 行：${order.customer||'未填写客户'} · ${order.requirement||'未填写需求'}`}
function showImportPreview(file,analysis){pendingImport={file,analysis};$('importFileName').textContent=`${file.name} · ${analysis.total} 条记录`;$('importTotalCount').textContent=analysis.total;$('importNewCount').textContent=analysis.newItems.length;$('importUpdateCount').textContent=analysis.updates.length;$('importDuplicateCount').textContent=analysis.duplicates.length;const duplicateNotice=$('duplicateNotice');duplicateNotice.classList.toggle('hidden',analysis.duplicates.length===0);$('duplicateExamples').innerHTML=analysis.duplicates.slice(0,5).map(item=>`<li>${esc(importExample(item))}</li>`).join('')+(analysis.duplicates.length>5?`<li>另有 ${analysis.duplicates.length-5} 条重复记录</li>`:'');const invalidNotice=$('invalidNotice');invalidNotice.classList.toggle('hidden',analysis.invalid.length===0);$('invalidTitle').textContent=`${analysis.invalid.length} 条记录无法导入`;$('invalidExamples').innerHTML=analysis.invalid.slice(0,5).map(item=>`<li>第 ${item.rowNumber} 行：${esc(item.error)}</li>`).join('')+(analysis.invalid.length>5?`<li>另有 ${analysis.invalid.length-5} 条格式错误</li>`:'');$('skipDuplicateImport').classList.toggle('hidden',analysis.duplicates.length===0);$('skipDuplicateImport').textContent=`跳过 ${analysis.duplicates.length} 条重复项`;$('confirmImport').textContent=analysis.duplicates.length?'仍然导入全部':`确认导入 ${analysis.valid.length} 条`;$('confirmImport').disabled=analysis.valid.length===0;$('importModal').classList.remove('hidden')}
async function handleImportFile(file){if(!file)return;if(!window.XLSX||!window.OrderImportUtils){toast('表格读取组件加载失败，请刷新页面重试');$('orderFileInput').value='';return}try{const buffer=await file.arrayBuffer();const workbook=XLSX.read(buffer,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error('表格中没有工作表');const rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:true});if(!rows.length)throw new Error('表格中没有订单记录');const analysis=OrderImportUtils.analyze(rows,orders);showImportPreview(file,analysis)}catch(error){console.error(error);toast(error.message||'表格读取失败，请检查文件格式');$('orderFileInput').value=''}}
async function commitImport(includeDuplicates){if(!pendingImport)return;const imported=OrderImportUtils.prepare(pendingImport.analysis,orders,includeDuplicates,Date.now());if(!imported.length){closeImportModal();toast('没有需要导入的订单');return}const buttons=[$('skipDuplicateImport'),$('confirmImport')];buttons.forEach(button=>button.disabled=true);try{await persistOrdersBatch(imported);const skipped=pendingImport.analysis.duplicates.length&&!includeDuplicates?pendingImport.analysis.duplicates.length:0;closeImportModal();switchView('orders');toast(skipped?`已导入 ${imported.length} 条，跳过 ${skipped} 条重复项`:`已导入 ${imported.length} 条订单`)}catch(error){console.error(error);buttons.forEach(button=>button.disabled=false);toast('批量上传失败，请检查网络后重试')}}
function initWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;try{ctx.registerTool({name:'list_orders',title:'查询订单',description:'按客户名称或状态查询当前共享订单。',inputSchema:{type:'object',properties:{query:{type:'string'},status:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:({query='',status=''})=>orders.filter(o=>(!query||o.customer.includes(query)||o.id.includes(query))&&(!status||o.status===status)).map(({id,customer,requirement,status,dueDate,amount,paid})=>({id,customer,requirement,status,dueDate,amount,paid}))});ctx.registerTool({name:'create_order',title:'新建订单',description:'创建一笔共享订单。',inputSchema:{type:'object',properties:{customer:{type:'string'},requirement:{type:'string'},amount:{type:'number'},dueDate:{type:'string'}},required:['customer','requirement'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input.customer?.trim()||!input.requirement?.trim())throw new Error('客户名称和需求不能为空');const o={id:`OD${iso(today).replaceAll('-','')}${String(Date.now()).slice(-3)}`,customer:input.customer.trim(),contact:'',requirement:input.requirement.trim(),amount:Number(input.amount||0),paid:0,owner:'管理员',dueDate:input.dueDate||'',priority:'普通',status:'需求确认中',contract:'未准备',invoice:'未申请',shipping:'未备货',payment:'未付款',logistics:[],carrier:'',tracking:'',feedback:'',notes:'',updated:Date.now()};await persistOrder(o);return{id:o.id,status:'created'}}})}catch(e){console.warn('WebMCP unavailable',e)}}
async function enterApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('loginError').textContent='';try{await loadSharedOrders();initWebMCP()}catch(error){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');$('loginError').textContent='共享数据加载失败，请稍后重试'}}
function restoreLoginSettings(){try{const saved=JSON.parse(localStorage.getItem(REMEMBER_KEY));if(saved?.username&&saved?.password){$('username').value=saved.username;$('password').value=saved.password;$('rememberPassword').checked=true}}catch{localStorage.removeItem(REMEMBER_KEY)}if(rememberActive())$('autoLogin30').checked=true;else if(rememberedUntil()){localStorage.removeItem(REMEMBER_UNTIL_KEY)}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='正在登录…';if(!client){$('loginError').textContent='云数据库尚未配置';return}if($('autoLogin30').checked)localStorage.setItem(REMEMBER_UNTIL_KEY,String(Date.now()+30*24*60*60*1000));else localStorage.removeItem(REMEMBER_UNTIL_KEY);const email=`${$('username').value.trim().toLowerCase()}@orderdesk.internal`;const {error}=await client.auth.signInWithPassword({email,password:$('password').value});if(error){localStorage.removeItem(REMEMBER_UNTIL_KEY);$('loginError').textContent='用户名或密码不正确';return}if($('rememberPassword').checked)localStorage.setItem(REMEMBER_KEY,JSON.stringify({username:$('username').value.trim(),password:$('password').value}));else localStorage.removeItem(REMEMBER_KEY);await enterApp()};
$('logoutBtn').onclick=async()=>{localStorage.removeItem(REMEMBER_UNTIL_KEY);await client.auth.signOut();location.reload()};
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
$('newOrderBtn').onclick=()=>openModal();$('newOrderTop').onclick=()=>openModal();$('addLogisticsBtn').onclick=()=>addLogisticsRow();$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('orderModal').onclick=e=>{if(e.target===$('orderModal'))closeModal()};
$('addContractFiles').onclick=()=>$('contractFileInput').click();$('addInvoiceFiles').onclick=()=>$('invoiceFileInput').click();$('contractFileInput').onchange=e=>{queueDocumentFiles('contract',e.target.files);e.target.value=''};$('invoiceFileInput').onchange=e=>{queueDocumentFiles('invoice',e.target.files);e.target.value=''};
$('uploadOrdersBtn').onclick=()=>{if(!window.XLSX){toast('表格读取组件尚未加载，请刷新页面重试');return}$('orderFileInput').value='';$('orderFileInput').click()};$('orderFileInput').onchange=e=>handleImportFile(e.target.files?.[0]);$('closeImportModal').onclick=closeImportModal;$('cancelImport').onclick=closeImportModal;$('importModal').onclick=e=>{if(e.target===$('importModal'))closeImportModal()};$('skipDuplicateImport').onclick=()=>commitImport(false);$('confirmImport').onclick=()=>commitImport(true);
$('orderForm').onsubmit=async e=>{e.preventDefault();const o=formOrder();const exists=orders.some(x=>x.id===o.id);const submitButton=e.submitter||$('orderForm').querySelector('button[type="submit"]');const originalText=submitButton.textContent;let uploadedPaths=[];submitButton.disabled=true;submitButton.textContent=pendingDocumentFiles.contract.length+pendingDocumentFiles.invoice.length?'正在上传附件…':'正在保存…';try{const result=await uploadPendingDocuments(o);uploadedPaths=result.uploadedPaths;await persistOrder(result.order);closeModal();toast(exists?'订单已更新':'订单已创建')}catch(error){if(uploadedPaths.length)await client.storage.from('order-documents').remove(uploadedPaths);console.error(error);toast('保存失败，请检查附件格式、网络或存储设置')}finally{submitButton.disabled=false;submitButton.textContent=originalText}};
$('deleteOrder').onclick=async()=>{const id=$('editingId').value;if(id&&confirm(`确定删除订单 ${id} 吗？此操作无法撤销。`)){try{await removeSharedOrder(id);closeModal();toast('订单已删除')}catch{toast('删除失败，请稍后重试')}}};
$('batchDeleteBtn').onclick=async()=>{const ids=[...selectedOrderIds];if(!ids.length)return;if(!confirm(`确定永久删除已选中的 ${ids.length} 个订单吗？此操作无法撤销。`))return;try{await removeSharedOrders(ids);toast(`已删除 ${ids.length} 个订单`)}catch{toast('批量删除失败，请稍后重试')}};
$('exportSelectedBtn').onclick=()=>{const selected=orders.filter(order=>selectedOrderIds.has(order.id));exportCsv(selected)};
$('orderSearch').oninput=renderOrders;$('statusFilter').onchange=renderOrders;$('ownerFilter').onchange=renderOrders;$('exportBtn').onclick=()=>{switchView('orders');toast('请勾选需要导出的订单')};
$('globalSearch').onkeydown=e=>{if(e.key==='Enter'){switchView('orders');$('orderSearch').value=e.target.value;renderOrders()}};
$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
$('dateLine').textContent=today.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'});
async function initialize(){restoreLoginSettings();if(!client){$('loginError').textContent='云数据库尚未配置';return}const {data}=await client.auth.getSession();if(data.session)await enterApp()}
initialize()
